### ISSUE TITLE
[Dupe] Shift+Right clicking with certain recipes fills your inventory

### ISSUE THREAD

**Issue by etil2jz** [Modflower/QuickBench#11]
### Environment

- **Minecraft**: 1.21.1 Client & Server
- **QuickBench**: 4.4.1
- **Loader**: Fabric
- **Java**: Adoptium 21.0.4.7
- **Mods**: /

### To Reproduce

1. Take a bed/wool with a dye, netherite ingot craft etc. (lots of possible combinations)
2. Open a crafting table
3. Place them in it
4. Shift+right click on the result, it will fill your inventory

### Expected results

To not dupe when shift+right clicking

### Logs, crash report, mod list or unmodified mod pack

https://github.com/user-attachments/assets/5e4bb294-2924-4b02-aa37-4263ed254796

**Comment by Ampflower** [comment]
Huh... surprised that didn't happen here in development.
