### ISSUE TITLE
Please mark QuickBench as compatible with Fabric on CurseForge

### ISSUE THREAD

**Issue by marlester-dev** [Modflower/QuickBench#12]
### What would you like added or changed?

The most of QuickBench versions are not marked as compatible with Fabric on curseforge and that's why I can't put it in my modpack because curseforge rejects it.
Please fix it, thanks very much in advance.

**Comment by Ampflower** [comment]
Fixed on CurseForge's side.

**Comment by Ampflower** [comment]
CurseGradle seems to be lacking support for manually marking supported platforms.

**Comment by Ampflower** [comment]
Fixed in v4.3.3, swapping to Darkhax's CurseForgeGradle plugin in the process.
Changes will be ported to 1.20.1- and 1.21+
