### ISSUE TITLE
No effect with Enhanced Workbenches' workbenches

### ISSUE THREAD

**Issue by unilock** [Modflower/QuickBench#2]
The mod [Enhanced Workbenches](https://github.com/Luligabi1/EnhancedWorkbenches) adds workbenches which simulate the beloved Crafting Station from Tinkers' Construct and Project Table from RedPower.

In a very large modpack (using Quilt 1.19.2), it seems there is no difference when batch crafting using Enhanced Workbenches' workbenches with or without QuickBench installed. I'm guessing it's because the mod [completely reimplements](https://github.com/Luligabi1/EnhancedWorkbenches/blob/1.19.2-ct/src/main/java/me/luligabi/enhancedworkbenches/common/screenhandler/CraftingBlockScreenHandler.java) vanilla's crafting logic?

I'm not sure if this can be fixed on QuickBench's end, but I figured it would be worth mentioning regardless, for posterity.

**Comment by Ampflower** [comment]
Yeah, it's known that those reimplement the logic on their own.

I could possibly try to optimise it on Quickbench's side, but there's not any guarantee that compatibility will be stable, as two distinct mods.

**Comment by unilock** [comment]
I've opened a PR to Enhanced Workbench to use QuickBench when it's present: https://github.com/Luligabi1/EnhancedWorkbenches/pull/9/commits/09cae7904ee1485c8a98d5f6360ff0e736212b25

Maybe there could be a QuickBench API to depend on, instead of ~~using a self-mixin to implement `CraftingInventoryDuck` and~~ directly referencing `MixinHooks`?

EDIT: I think I may be going about this the wrong way :P

**Comment by Ampflower** [comment]
Not sure what'd be an ideal way to implement such an API if I'll be honest. Directly using MixinHooks likely is decent enough for most cases at least, ignoring that custom inventories apparently don't take too well to the existing API.

**Comment by unilock** [comment]
Well, Enhanced Workbenches now has explicit support for QuickBench, so I'll close this.
